"""Quality evaluation tests for PaperPilot Phase 4 using DeepEval.

Measures AI quality of answers generated by the workflow.
Separate from structural evaluation - these scores answer "Was the answer good?"
not "Did the agent behave correctly?".
"""

import os
import sys
import asyncio
import re

sys.path.insert(0, r'C:\Users\ASUS\Desktop\PaperPilot AI\backend')

from deepeval.metrics import (
    AnswerRelevancyMetric,
    FaithfulnessMetric,
    ContextualRelevancyMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
)
from deepeval.test_case import LLMTestCase

sys.path.insert(0, r'C:\Users\ASUS\Desktop\PaperPilot AI\backend')

from generation.workflow import workflow
from generation.nodes import academic_search_node, query_understanding_node, router_node, generate_node, relevance_check_node
from generation.state import create_initial_state, AgentState


# ──────────────────────────────────────────────
# Quality Evaluation Functions
# ──────────────────────────────────────────────

async def run_workflow_for_eval(query: str, conversation_id: str = "eval-test") -> dict:
    """Run the compiled LangGraph workflow and return the final state."""
    initial_state = {
        "conversation_id": conversation_id,
        "user_query": query,
        "messages": [],
        "intent": "general_answer",
        "response": "",
    }

    final_state = None
    async for chunk in workflow.astream(initial_state, config={"configurable": {"thread_id": conversation_id}}):
        final_state = chunk

    if final_state is None:
        final_state = await workflow.ainvoke(initial_state, config={"configurable": {"thread_id": conversation_id}})

    return final_state


async def get_evaluation_data(query: str) -> dict:
    """Run workflow and extract data needed for DeepEval evaluation."""
    state = await run_workflow_for_eval(query)

    answer = state.get("response", "") or ""

    # Extract context from ranked papers and academic papers
    contexts = []
    ranked_papers = state.get("ranked_papers", [])
    for paper in ranked_papers[:3]:  # Top 3 ranked papers
        ctx = paper.title or ""
        if paper.abstract:
            ctx += ". " + str(paper.abstract)[:200]
        contexts.append(ctx)

    # Get citations from citation validation
    citations = state.get("citations", [])

    return {
        "answer": answer,
        "contexts": contexts,
        "citations": citations,
    }


# ──────────────────────────────────────────────
# Quality Test Cases
# ──────────────────────────────────────────────

QUALITY_TEST_CASES = [
    {
        "name": "local_rag_answer_relevancy",
        "query": "What do the uploaded papers say about RAG evaluation techniques?",
    },
    {
        "name": "academic_answer_faithfulness",
        "query": "Find recent papers about RAG evaluation benchmarks",
    },
    {
        "name": "contextual_relevancy_check",
        "query": "What are the key challenges of Retrieval-Augmented Generation?",
    },
]


# ──────────────────────────────────────────────
# DeepEval Quality Evaluation
# ──────────────────────────────────────────────

def run_deepeval_quality_evaluation(test_cases: list) -> dict:
    """Run DeepEval quality evaluation on the given test cases."""
    results = {}

    for case in test_cases:
        name = case["name"]
        query = case["query"]

        print(f"\nRunning DeepEval for: {name}")
        print(f"Query: {query}")

        # Get evaluation data from workflow
        eval_data = asyncio.run(get_evaluation_data(query))

        # Create DeepEval test case
        deepeval_case = LLMTestCase(
            input=query,
            actual_output=eval_data["answer"],
            retrieval_context=eval_data["contexts"],
        )

        # Initialize metrics
        metrics = [
            AnswerRelevancyMetric(),
            FaithfulnessMetric(),
            ContextualRelevancyMetric(),
        ]

        # Run each metric and collect scores
        metric_scores = {}
        for metric in metrics:
            try:
                score = metric.measure(deepeval_case)
                metric_scores[metric.name] = score
                print(f"  {metric.name}: {score:.2f}")
            except Exception as e:
                print(f"  {metric.name}: ERROR - {type(e).__name__}: {e}")
                metric_scores[metric.name] = 0.0

        results[name] = {
            "answer": eval_data["answer"],
            "contexts": eval_data["contexts"],
            "metric_scores": metric_scores,
        }

    return results


# ──────────────────────────────────────────────
# Citation Evaluation
# ──────────────────────────────────────────────

def run_citation_evaluation(test_cases: list) -> dict:
    """Run deterministic citation evaluation checks."""
    results = {}

    for case in test_cases:
        name = case["name"]
        query = case["query"]

        print(f"\nRunning citation evaluation for: {name}")

        # Run workflow to get state
        state = asyncio.run(get_evaluation_data(query))

        answer = state["answer"]
        citations = state["citations"]

        # Deterministic citation checks
        citation_results = {
            "total_citations_in_answer": len(re.findall(r"\[Paper \d+\]", answer))
                              + len(re.findall(r"\[Source \d+\]", answer)),
            "citations_validated": sum(1 for c in citations if c.get("valid", False)),
            "citations_total": len(citations),
            "all_citations_have_source": all(
                c.get("details", "").find("exists in context") >= 0
                or c.get("valid", False)
                for c in citations
            ),
        }

        results[name] = {
            "answer": answer,
            "citations": citations,
            "citation_results": citation_results,
        }

    return results